---
kind: pipeline
name: notify-slack-pipeline-start
  
clone: 
  disable: true
 
steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: 
        from_secret: SLACK_CHANNEL
      template: >
        {{#if build.pull }}
          *Build started on {{ uppercasefirst repo.name}}* ({{ repo.owner }}/{{ repo.name }}) - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
          *Build started on {{ uppercasefirst repo.name}} ({{ repo.owner }}/{{ repo.name }}) - Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>      
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> 
        Author: {{ build.author }} 
        <{{ build.link }}|Visit build page 👁>

---
kind: pipeline
name: build-docker-image

steps:
  - name: build-docker-build-stage
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO,,}
      target: build-stage
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}-builder
      cache_from:
        - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}-builder
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        exclude:
          - tags
      branch:
        exclude:
          - master
          - develop

  - name: build-docker-image-master
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO,,}
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}
      cache_from:
        - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      branch:
        - master
        - develop
      event:
        exclude:
          - tag

depends_on :
  - notify-slack-pipeline-start
---
kind: pipeline
name: tests

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
   
  - name: install-dependencies
    image: node
    commands:
      - npm install
   
  - name: save-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
       - ./node_modules
    volumes:
      - name: cache
        path: /cache
  
  - name: test-unit
    image: node
    commands:
      - npm run test

depends_on:
  - notify-slack-pipeline-start

---
kind: pipeline
name: deploy

steps: 
  - name: deploy-caprover-stage
    image: node:10-slim
    commands:
      - npm i -g caprover
      - caprover login -u $CAPROVER_URL -p $CAPROVER_PASSWORD -n $CAPROVER_NAME
      - export APP_NAME_LOWERCASE=$(echo $APP_NAME | tr '[:upper:]' '[:lower:]')
      - CAPROVER_CONFIG_FILE='./config.json' caprover api && echo
     # - caprover deploy -a $APP_NAME_LOWERCASE-i $DOCKER_REGISTRY:${DRONE_SOURCE_BRANCH/\//-}-builder
      - caprover logout
    environment:
      CAPROVER_URL:
        from_secret: CAPROVER_URL
      CAPROVER_PASSWORD:
        from_secret: CAPROVER_PASSWORD
      CAPROVER_NAME:
        from_secret: CAPROVER_NAME
      APP_NAME: ${DRONE_SOURCE_BRANCH/\//-}-shound-api
    branch:
      exclude:
        - master
        - develop

depends_on:
  - build-docker-image
  - tests

---
kind: pipeline
name: notify-slack-pipeline-end

clone: 
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel:
        from_secret: SLACK_CHANNEL
      template: >
        {{#if build.pull }}
          *{{#success build.status}}🎉{{ else }}❌{{/success}} {{ uppercasefirst build.status }}*: {{ repo.owner }}/{{ repo.name }} - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
          *{{#success build.status}}🎉{{ else }}❌{{/success}} {{ uppercasefirst build.status }}: {{ repo.owner }}/{{ repo.name }} - Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        Duration: {{ since build.created }}
        <{{ build.link }}|Visit build page 👁>

depends_on:
  - build-docker-image
  - tests

trigger:
  status:
    - success
    - failure

---
kind: pipeline
name: notify-slack-deploy

clone: 
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel:
        from_secret: SLACK_CHANNEL
      template: >
        *{{#success build.status}}
           🎉 Deploy succeed
        {{ else }}
          ❌ Deploy Failed
        {{/success}} 
        {{ uppercasefirst build.status }}*: {{ repo.owner }}/{{ repo.name }}
        
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        Duration: {{ since build.created }}

depends_on:
  - deploy

trigger:
  status:
    - success
    - failure
