

---

kind: pipeline
name: slack-notify

  - name: slack
    image: plugins/slack
    detach: true
    settings:
      webhook: 
        from_secret: slack-hook
      channel: dev-status
      template: >
        {{#success build.status}}
          Build {{build.number}} on ${DRONE_BRANCH} succeeded 🚀

          Commit: ${DRONE_COMMIT_MESSAGE} - ${DRONE_COMMIT_AUTHOR}
          ${DRONE_COMMIT_LINK}
          
          Good job 💪.
        {{else}}
          Build {{build.number}} on ${DRONE_BRANCH} failed 😱 
          Commit: ${DRONE_COMMIT_MESSAGE}  - ${DRONE_COMMIT_AUTHOR}
          ${DRONE_COMMIT_LINK} 

          Following steps have failed: ${DRONE_FAILED_STAGES}
          
          Fix me please 💉.
        {{/success}}

  
        
  - name: slack-deploy-success
    image: plugins/slack
    detach: true
    depends_on: deploy
    when:
      status:
      - success
    settings:
      webhook: 
        from_secret: dev-status
      channel: shound-changes
      template: >
              A new Build as been deployed 🚀
    
              Commit: ${DRONE_COMMIT_MESSAGE} - ${DRONE_COMMIT_AUTHOR}
              ${DRONE_COMMIT_LINK}
              
              Good job 💪.

  - name: slack-deploy-fail
    image: plugins/slack
    detach: true
    depends_on: deploy
    when:
      status:
         failure
    settings:
      webhook: 
        from_secret: dev-status
      channel: dev-status
      template: >
        Deploy failed 😱 
        Requested by: ${DRONE_COMMIT_AUTHOR} 
            
        Following steps have failed: ${DRONE_FAILED_STAGES}
        
        Fix me please 💉.





        {{#if build.pull }}
        *Build started on {{ uppercasefirst repo.name}}* ({{ repo.owner }}/{{ repo.name }}) - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
      {{else}}
        *Build started on {{ uppercasefirst repo.name}} ({{ repo.owner }}/{{ repo.name }}) - Build #{{ build.number }}* (type: `{{ build.event }}`)
      {{/if}}
      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>          
      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
      Author: {{ build.author }}
      <{{ build.link }}|Visit build page 👁>


      #
#---
#kind: pipeline
#name: code-check

#steps:
#  - name: code-analysis
#    image: aosapps/drone-sonar-plugin
#    settings:
#      sonar_host:
#        from_secret: SONAR_HOST
#      sonar_token:
#        from_secret: SONAR_TOKEN
        