---
  kind: pipeline
  name: Slack notify for pipeline start
  
  clone: 
    disable: true

  steps:
    - name: slack
      image: plugins/slack
      settings:
        webhook:
          from_secret: SLACK_WEBHOOK
        channel: 
          from_secret: SLACK_CHANNEL
        link_names: true
        template: >
          {{#if build.pull }}
            *Build started on {{ uppercasefirst repo.name}}* ({{ repo.owner }}/{{ repo.name }}) - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
          {{else}}
            *Build started on {{ uppercasefirst repo.name}} ({{ repo.owner }}/{{ repo.name }}) - Build #{{ build.number }}* (type: `{{ build.event }}`)
          {{/if}}
          Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>          
          Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
          Author: {{ build.author }}
          <{{ build.link }}|Visit build page 👁>
#
#---
#kind: pipeline
#name: code-check

#steps:
#  - name: code-analysis
#    image: aosapps/drone-sonar-plugin
#    settings:
#      sonar_host:
#        from_secret: SONAR_HOST
#      sonar_token:
#        from_secret: SONAR_TOKEN
---
kind: pipeline
name: build-docker-image

steps:
  - name: build-docker-build-stage
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO,,}
      target: build-stage
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}-builder
      cache_from:
        - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}-builder
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      event:
        exclude:
          - tags
      branch:
        exclude:
          - master
          - develop

  - name: build-docker-image-master
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO,,}
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}
      cache_from:
        - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      branch:
        - master
        - develop
      event:
        exclude:
          - tag

---
kind: pipeline
name: tests

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
   
  - name: install-dependencies
    image: node
    commands:
      - npm install
   
  - name: save-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
       - ./node_modules
    volumes:
      - name: cache
        path: /cache
  
  - name: test-unit
    image: node
    commands:
      - npm run test-unit
    depends_on: install-dependencies
  
  - name: test
    image: node
    commands:
      - npm run test-end-to-end
    depends_on: install-dependencies

---
kind: pipeline 
type: ssh
name: deploy

steps:
  - name: deploy
    commands :
      - docker pull ${DRONE_SOURCE_BRANCH/\//-}
      - docker ps
   # when:
    #  branch:
     #   - master

server:
  host: 
    from_secret: DEPLOY_HOST_IP
  user: 
    from_secret: DEPLOY_HOST_USER
  password:
    from_secret: DEPLOY_HOST_PASSWORD

---
kind: pipeline
name: Slack notify for pipeline end

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel:
        from_secret: SLACK_CHANNEL
      link_names: true
      template: >
        {{#if build.pull }}
          *{{#success build.status}}🎉{{ else }}❌{{/success}} {{ uppercasefirst build.status }}*: {{ repo.owner }}/{{ repo.name }} - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
          *{{#success build.status}}🎉{{ else }}❌{{/success}} {{ uppercasefirst build.status }}: {{ repo.owner }}/{{ repo.name }} - Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        Duration: {{ since build.created }}
        <{{ build.link }}|Visit build page 👁>

depends_on:
  - build-docker-image
  - tests

trigger:
  status:
    - success
    - failure
