kind: pipeline
type: docker 
name: default

steps:
  - name: tests
    image: node
    commands:
      - npm install
      - npm run test

  - name: build test image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t shound-front:${DRONE_COMMIT} .
  
